#服务器端口
server:
  port: ${sealtalk-config.server_port}
  servlet:
    encoding:             #解决中文乱码问题，同一使用UTF-8编码
      charset: UTF-8
      force: true
      enabled: true
      force-request: true
      force-response: true

spring:
  profiles:
    active: dev      # 环境配置 dev 开发环境，pro 生产环境
  flyway:
    enabled: true
    # 禁止清理数据库表
    clean-disabled: true
    baseline-description: baselines
    # 如果数据库不是空表，需要设置成 true，否则启动报错
    baseline-on-migrate: false
    baseline-version: 2
  swagger2:
    enabled: false

#MyBatis 是一款优秀的持久层框架
mybatis:
  mapper-locations: classpath:mybatis/*.xml

sealtalk:
  datasource:
    driverclassname: com.mysql.jdbc.Driver
    url: jdbc:mysql://${sealtalk-config.db_host}:${sealtalk-config.db_port}/${sealtalk-config.db_name}?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8&useCompress=true
    username: ${sealtalk-config.db_user}
    password: ${sealtalk-config.db_password}
    maximum-pool-size: 10